# Generated by Django 5.1.1 on 2024-10-01 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_id', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='career_goal',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_taken_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_taken_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_taken_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_job_profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_work_experience_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_work_experience_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_work_experience_years',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hard_skills_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hard_skills_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hard_skills_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_job_profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_work_experience_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_work_experience_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_work_experience_years',
        ),
        migrations.RemoveField(
            model_name='student',
            name='soft_skills_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='soft_skills_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='soft_skills_3',
        ),
        migrations.CreateModel(
            name='SkillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_taken_1', models.CharField(max_length=100)),
                ('grades_1', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('course_taken_2', models.CharField(blank=True, max_length=100)),
                ('grades_2', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('course_taken_3', models.CharField(blank=True, max_length=100)),
                ('grades_3', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('certifications', models.TextField(blank=True)),
                ('hard_skills_1', models.CharField(max_length=100)),
                ('hard_skills_2', models.CharField(blank=True, max_length=100)),
                ('hard_skills_3', models.CharField(blank=True, max_length=100)),
                ('soft_skills_1', models.CharField(max_length=100)),
                ('soft_skills_2', models.CharField(blank=True, max_length=100)),
                ('soft_skills_3', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_work_experience_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance')], max_length=10, verbose_name='Previous Work Experience Type')),
                ('previous_work_experience_years', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='Previous Work Experience Years')),
                ('previous_job_profile', models.CharField(max_length=100, verbose_name='Previous Job Profile')),
                ('previous_work_experience_at', models.CharField(max_length=100, verbose_name='Previous Work Experience At')),
                ('current_work_experience_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance')], max_length=10, verbose_name='Current Work Experience Type')),
                ('current_work_experience_years', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='Current Work Experience Years')),
                ('current_job_profile', models.CharField(max_length=100, verbose_name='Current Job Profile')),
                ('current_work_experience_at', models.CharField(max_length=100, verbose_name='Current Work Experience At')),
                ('interests', models.TextField(blank=True, verbose_name='Interests')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('career_goal', models.TextField(blank=True, verbose_name='Career Goal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
